### ISSUE TITLE
Manual for MultiBUGS script?

### ISSUE THREAD

**Issue by hszest** [MultiBUGS/MultiBUGS#11]
R2MultiBUGS keeps failing, and I've noticed that there are may be differences between the  traditional BUGS script and the MultiBUGS script, such as the call like `modelDistribute()`, is there a manual for MultiBUGS script? Thanks.

**Comment by rjbgoudie** [comment]
I think your problem with R2MultiBUGS is because it only works with 1.0, not the currently released version 0.9 - see https://github.com/MultiBUGS/R2MultiBUGS/issues/1#issuecomment-423926540

There is documentation for the scripting language within MultiBUGS in Manuals > MultiBUGS User Manual > Scripts and Batch-mode. This hadn't been updated to include `modelDistribute()` until just now (2c6782d853a253d27fb2e2b6541f5123e24ca14d), but does now. `modelDistribute()` is the only important addition - it takes one integer argument that is the number of workers/cores you want to use.

Hope that helps.

**Comment by hszest** [comment]
Thanks for your comments and I will look into the documents carefully.
MultiBUGS really helped me A LOT with my current project (after trying literally every sampler I can find), thank you again!

**Comment by rjbgoudie** [comment]
Glad to hear MultiBUGS is helping you 👍
