### ISSUE TITLE
Censored dnorm as prior

### ISSUE THREAD

**Issue by MLIrstea** [MultiBUGS/MultiBUGS#29]
Hi,
I've tried to use a censored normal distribution as prior to a latent variable and i get the following error: 
BugsCmds.SetFilePath( 'C:/Users/.../inits1.txt' ); BugsCmds.LoadInitsGuard; BugsCmds.specificationDialog.chain := 1; BugsCmds.LoadInits
error for node T of type dnorm node censored node can not be used as prior

I ran multibugs from R using the R2MultiBUGS package. I've also ran the same model with openbugs from R without trouble.

A short overview of the hierarchical model :
T0 ~ dnorm(0,1.0E-6)C(0,)
for( i in 1 : n ) {
  T[i] ~ dnorm(T0,tau.T0)C(0,)
  }

Thanks

**Comment by rjbgoudie** [comment]
Thanks for the report.

This is actually deliberate: MultiBUGS doesn't allow censoring of latent (i.e. unobserved) quantities, since censoring represents an observation e.g. you observed something to weigh more than 100kg, say. It is not obvious what "censoring" a latent quantity means.

The fix depends on whether T[i] is observed or not - i.e. is there data T[i]?

If T[i] is observed, all you need to do is change the first C(0, ) to T(0, ) - which means that T0 is now regarded as truncated rather than censored. Then you should get the same results as you get from OpenBUGS. This is because the normalising constant formed by truncation is a true constant here (it will be 0.5 in this case).

If T[i] is unobserved, it is unclear what the resolution is - it depends on what you are really trying to do. What OpenBUGS is doing in this case is strange and probably "wrong" - it just uses the Gaussian density function for the T[i], but rejects any value below 0. This is "wrong" because the implied "density" does not integrate to 1, as required for by the definition of a density. So while OpenBUGS is giving results, it not at all clear what the interpretation is. Instead, you could truncate T[i]. However note that truncation will add a normalising constant (so that the density integrates to 1), which will depend on T0. Also, if you truncate T[i] the prior mean of T[i] is NOT T0 - it will be higher than T0 since you have excluded all values less than zero. So you have to be careful with interpretation. Alternatively you could use an unrestricted prior and then use the abs() function make it positive before feeding into the model.

Hope that makes sense?
