### ISSUE TITLE
Problem with distribute

### ISSUE THREAD

**Issue by emmanuellesaffre** [MultiBUGS/MultiBUGS#33]
Dear,

I have installed MultiBUGS according to the specification, and also Microsoft MPI. When I first used the option distribute, administrator rights were asked and were granted. However, in 2 cases (both multiple chains, and one hierarchical model) the sampling was not distributed over the three cores. This is strange, because when I looked at the Task Manager then three BUGSWorker.exe programs seem to be active, together with OpenBUGS.exe. I also never received an error. So I am puzzled why the cores are not activated. When I compared the processing time with MultiBUGS and with OpenBUGS, I found out they were the same.

Any help is appreciated.

Emmanuel Lesaffre

**Comment by emmanuellesaffre** [comment]
Dear,

Indeed I see three versions of BUGSworker.exe on Task Manager when I initiate 3 chains and I ask to distribute to 3 cores, but:

-        When I ask MultiBUGS for information Info>Distribution then I see that only 1 Logical processor is taken

-        Then, when I run 3 chains in parallel and aks for each chain 150,000 iterations to do (for a simple linear regression model), then the time needed by OpenBUGS is exactly the same as for MultiBUGS. This not only happens with me, but also on three other laptops and also happens with a hierarchical logistic regression model

So, my conclusion is that perhaps parallel computing is done but perhaps there is problem with the link between what the BUGSworker.exe programs are doing what we receive as result

Thanks for your help


Kind regards

Emmanuel Lesaffre

-------------------------------------------------------------------------------------------------------------------------
Professor emeritus Biostatistics
L-Biostat, School of Public Health, KULeuven University of Leuven, Belgium
Kapucijnenvoer 35, 2nd Floor, B-3000 Leuven, BELGIUM
Tel: +32 16 37 33 64| Fax: + 32 16 33 70 15 | Tel secr: +32 16 37 33 89
E-mail: emmanuel.lesaffre@kuleuven.be<mailto:emmanuel.lesaffre@med.kuleuven.be> | Website: https://ibiostat.be
Honorary Professor, Erasmus MC, Rotterdam, the Netherlands
-------------------------------------------------------------------------------------------------------------------------

**Comment by emmanuellesaffre** [comment]
Hi,

Did you receive my reply?


Kind regards

Emmanuel Lesaffre

-------------------------------------------------------------------------------------------------------------------------
Professor emeritus Biostatistics
L-Biostat, School of Public Health, KULeuven University of Leuven, Belgium
Kapucijnenvoer 35, 2nd Floor, B-3000 Leuven, BELGIUM
Tel: +32 16 37 33 64| Fax: + 32 16 33 70 15 | Tel secr: +32 16 37 33 89
E-mail: emmanuel.lesaffre@kuleuven.be<mailto:emmanuel.lesaffre@med.kuleuven.be> | Website: https://ibiostat.be
Honorary Professor, Erasmus MC, Rotterdam, the Netherlands
-------------------------------------------------------------------------------------------------------------------------

**Comment by rjbgoudie** [comment]
Yes, but I’m still puzzled I’m afraid. I have some more questions/comments that might help to isolate the problem.

Just to confirm, you are using MultiBUGS 1.0? Also, do you get results from all 3 chains if you look at the output?

Note that if you run 3 chains, with “num cores”=3, it won’t parallelise WITHIN each chain, regardless of whether it is possible: each chain will use 1 of the 3 cores. Hence why Info>”Show Distribution” is probably showing “Number of processor: 1”. What does Info > Distribution Info say?

The problem could be either (1) MultiBUGS is not setup quite correctly on your computer; (2) your specific model(s) do not parallelise efficiently in MultiBUGS; or (3) a bug in MultiBUGS; or (4) something else..!

To standardise on a model I know about, could you try the Methadone example from Examples > Examples Vol IV > Methadone, and compare run times for "1 chain, with no distribution" (don’t click distribute at all) vs "1 chain, with 2 cores"? I suggest only trying to run a few iterations, since it will be very slow with only 1 or 2 cores. e.g. on my current computer 50 iterations takes ~20s (no distribute) vs ~10s with 2 cores.

Sorry again that you are having problems - hopefully we can figure it out.

**Comment by emmanuellesaffre** [comment]
Dear,

When I apply MultiBUGS on your example, then I get for 50 iterations:
15s with 1 core
8s with 2 cores
And Info>Distribution now talks of 2 processors
So the program seems to work.

I then tried 2 chains with
2 cores: 17s
1 core: does not work
4 cores: 9s

So for this example the program appears to work.

Is there a reason why there is no gain when I apply it a simple regression analysis (I include the program) when I run 150000 iterations with 3 chains and distribute =3, compared to 150000 iterations with 3 chains and distribute  = 1?


Kind regards

Emmanuel Lesaffre

-------------------------------------------------------------------------------------------------------------------------
Professor emeritus Biostatistics
L-Biostat, School of Public Health, KULeuven University of Leuven, Belgium
Kapucijnenvoer 35, 2nd Floor, B-3000 Leuven, BELGIUM
Tel: +32 16 37 33 64| Fax: + 32 16 33 70 15 | Tel secr: +32 16 37 33 89
E-mail: emmanuel.lesaffre@kuleuven.be<mailto:emmanuel.lesaffre@med.kuleuven.be> | Website: https://ibiostat.be
Honorary Professor, Erasmus MC, Rotterdam, the Netherlands
-------------------------------------------------------------------------------------------------------------------------

**Comment by emmanuellesaffre** [comment]
Forgot to include the example


Kind regards

Emmanuel Lesaffre

-------------------------------------------------------------------------------------------------------------------------
Professor emeritus Biostatistics
L-Biostat, School of Public Health, KULeuven University of Leuven, Belgium
Kapucijnenvoer 35, 2nd Floor, B-3000 Leuven, BELGIUM
Tel: +32 16 37 33 64| Fax: + 32 16 33 70 15 | Tel secr: +32 16 37 33 89
E-mail: emmanuel.lesaffre@kuleuven.be<mailto:emmanuel.lesaffre@med.kuleuven.be> | Website: https://ibiostat.be
Honorary Professor, Erasmus MC, Rotterdam, the Netherlands
-------------------------------------------------------------------------------------------------------------------------

**Comment by rjbgoudie** [comment]
Glad we’re making a little progress. Across-chain parallelisation should work for any model, so I’m not sure why it isn’t working for you.

I guess you attached the fiels to the email, but it seems that email attachments don’t get passed through via GitHub. Can you please attach the files directly to the issue on GitHub? (Or email direct to me if you don’t want it in the public domain)

**Comment by emmanuellesaffre** [comment]
Thanks
What your email address?
Emmanuel

**Comment by rjbgoudie** [comment]
Resolved offline but for future reference: each MCMC step of the model is quite fast so if refresh=100, then the communication time dominates everything else.

For 100,000 iterations, with 3 chains, with refresh=100 we get:
3 cores in MultiBUGS: 62 seconds
1 core in MultiBUGS: 62 seconds

With refresh=100000:
3 cores in MultiBUGS: 1 second
1 core in MultiBUGS: 4 seconds

The setting of refresh makes a big difference because at each refresh all the cores must communicate their results to the master process, so that any trace plots etc can be updated. When each MCMC step is quite fast, as here, this communication overhead dominates.
