### ISSUE TITLE
meet error when recompiling   

### ISSUE THREAD

**Issue by alvincheng75** [MultiBUGS/MultiBUGS#46]
Log info :compiling "MathRandnum"
 one error detected

	IMPORT
		Math, Meta, Stores := Stores64 **X Symbol file of imported module not found** ; 
 where is the Stores64? 
 Anyway, Thanks a lot!

**Comment by rjbgoudie** [comment]
Stores64 is part of BlackBox. Does that help?

**Comment by alvincheng75** [comment]
I added the BlackBox directory to OS's Environment Path， not work。

**Comment by rjbgoudie** [comment]
Hi, I’m not sure what you are trying to do. Are you compiling MultiBUGS from source? If so, which version? What steps have you completed? I’m afraid compiling from source is quite intricate, so it will take much more details to figure out what is going wrong for you.

**Comment by alvincheng75** [comment]
I just use the Github downloaded version to recompile according to the Github recompile Guide .The first error is ''can not find environment.odc" , after I handled that , it comes "Symbol file of imported module not found", which points to the Stores64.
So I have to use the pre-build version , for multibugs1.0 meet several errors while OpenBugs does not, for example," the undefined real results" error.

**Comment by alvincheng75** [comment]
PS:
   I  can easily re-meet the problem by using two win10 64bit Computers.

**Comment by alvincheng75** [comment]
And why not providing 64bit version MultiBugs?

**Comment by rjbgoudie** [comment]
Hi, sorry for the very long delay in replying.

For future reference, you shouldn’t get any of these errors if you follow [these instructions](https://github.com/MultiBUGS/MultiBUGS#compiling-from-source-on-windows). Step 4 is the critical step to avoid needing to copy anything across from BlackBox.

The "the undefined real results” error may be due to MultiBUGS and OpenBUGS using different pseudo random number generation, or due to different sampling algorithms : it may be OpenBUGS is just lucky to avoid numerical issues. Or it could be a real bug in MultiBUGS, but we’d need to look at the exact model to debug this. Sorry not to be able to be more helpful.
