### ISSUE TITLE
Undefined Real Result when using modelDistribute()

### ISSUE THREAD

**Issue by elizmac6363** [MultiBUGS/MultiBUGS#50]
I am trying to speed up my run times, and so have downloaded MultiBUGS to make use of the modelDistribute() command. 

When I try to distribute the model over any number of cores, a black box error "undefined real result" shows up. I suspect this is an issue with the modelDistribute() command, as when I run the problem on only 1 core (i.e. not distributed), it always runs to completion and produces reasonable results. 

I have tried adjusting the refresh parameter in the modelUpdate() command (per https://github.com/MultiBUGS/MultiBUGS/issues/33) but the problem persists. 

Any advice on how to resolve this? Thanks!

**Comment by rjbgoudie** [comment]
Hi, sorry for the very slow reply.

I imagine you have long since given up, but if not, it may be worth trying tweaking the `inits` - “undefined real result” indictates the MCMC sampler is hitting some extreme part of the posterior. When the model is distributed, different pseudo-random numbers are used, so tweaking the initial values a little might help.

Otherwise, I’d have to look at the details of the specific model/data to see if I can spot the problem, if it is public/shareable.

Closing this issue for now, since assuming you have found another solution in the meantime, but feel free to reopen if you are still interested in finding a solution.
