### ISSUE TITLE
Possible incompatibility with latest version of Microsoft MPI?

### ISSUE THREAD

**Issue by GeoffHeard** [MultiBUGS/MultiBUGS#57]
Hi there,

I've had to re-install MultiBUGS on my machine after having the drive replaced. However, I now get an error when I attempt to run the MultiBUGS exe file - "Windows cannot find 'mpiexec'....". I've installed the MS-MPI file as per the MultiBUGS installation instructions. No problems in the install that I can see, but I can find no trace of 'mpiexec'. Could there have been a change with the latest version of MS-MPI that's causing the issue? Previous successful install on this machine was circa 3 months ago.

Greatly appreciate any assistance. MultiBUGS is a fantastic resource!

Cheers,

Geoff

**Comment by rjbgoudie** [comment]
Hi Geoff,

Current MS-MPI (v10.1.2) works fine for me with MultiBUGS 1.0 on Windows Server 2019 (a clean install on a fresh image), so I don’t think that can be the problem.

1. Can you check `mpiexec.exe` exists? It is usually installed in `C:\Program Files\Microsoft MPI\Bin`

2. If so, I suspect Windows is not finding `mpiexec` due to something a problem with the PATH environment variable. This will need to include the path to the folder containing `mpiexec.exe`, e.g. `C:\Program Files\Microsoft MPI\Bin`, otherwise Windows won’t find it. PATH should have been set for you when you installed MS-MPI, but perhaps it was not for some reason? How to edit PATH varies between each version of Windows: https://www.computerhope.com/issues/ch000549.htm is a reasonable gude to some of the methods.

Hope that helps.

**Comment by GeoffHeard** [comment]
Hi Rob,

Thanks for this. Not sure if it was from my end, or from Microsoft's end, but it looks like the source of my issues was failure of MS-MPI to properly install. Downloading the latest version today has solved the problem - installed properly and I'm away!

Thanks again,

Geoff

**Comment by rjbgoudie** [comment]
Glad to hear it is working now!
