### ISSUE TITLE
multibugs error

### ISSUE THREAD

**Issue by amirtei** [MultiBUGS/MultiBUGS#8]
Hi i have installed multibugs in my labtop and run my model but after around 30000 sample generating, multibugs stop and hanged. do you knew what is the problem and how to fux it. thank you for your help.

**Comment by rjbgoudie** [comment]
Sorry that you are having problems. Are you able to send us a copy of the model and data that you are using (or ideally a simplified version that also produces the error)? Without this, it will be difficult to identify the source of the problem.

**Comment by rjbgoudie** [comment]
This is fixed by https://github.com/MultiBUGS/MultiBUGS/commit/77f5efbe92b466920b8b48a16f6241a826b4ab3a and https://github.com/MultiBUGS/MultiBUGS/commit/da649f081be795c47ada826fd9e3cfc4331b681e . The compile error was to do with MarkChildren problems; the numerical issues are tricky and deep within the Delayed Rejection Metropolis algorithm, so Andrew turned this off for generic reals for now.
