### ISSUE TITLE
Saving outputs when Scripting MultiBUGS

### ISSUE THREAD

**Issue by aspassiani** [MultiBUGS/MultiBUGS#9]
I'm trying to use MultiBUGS through scripting but I'm having issues saving the outputs in the same way I did with OpenBUGS or WinBUGS. My script has the following lines:

> samplesCoda("*",'C:/Users/Documents/bayesian_output/tmp/coda_era_b10_i20_aws_1')

> samplesStats("*", 'C:/Users/Documents/bayesian_output/tmp/stats_era_b10_i20_aws_1')

> samplesDensity("*",'C:/Users/Documents/bayesian_output/tmp/log_era_b10_i20_aws_1.odc')

> samplesHistory("*",'C:/Users/Documents/bayesian_output/tmp/history_era_b10_i20_aws_1.txt')

> modelSaveLog('C:/Users/Documents/bayesian_output/tmp/log_era_b10_i20_aws_1.txt')

But this results in a trap error when used with MultiBUGS

There are no issues when I just type :

> samplesCoda("*")

> samplesStats("*")

> samplesDensity("*")

> samplesHistory("*")

> modelSaveLog('C:/Users/Documents/bayesian_output/tmp/log_era_b10_i20_aws_1.txt')

But since I will be running multiple scripts I was wondering if MultiBUGS just has a different way to automatically save the out into a specified file. 

Thanks for the help,
Alessio

**Comment by rjbgoudie** [comment]
Thanks for the clear bug report, apologies for the delay in fixing. The bugs in samplesCoda() and modelSaveLog() were fixed by c8e72ed8d9959cc7871258555e94bf316ccc76da

As far as I can see, samplesStats, samplesDensity and samplesHistory never had two arguments in OpenBUGS or WinBUGS, so I'm not sure what you expect the two argument version to do. What version of OpenBUGS/WinBUGS were you using for the top script?

**Comment by aspassiani** [comment]
Thanks for fixing the bugs in sampleCoda() and modelSaveLog().

I don't remember what I was doing with samplesStats, samplesDensity and samplesHistory in that top script. I might have copied an old version of a script where I was hoping there would be a way to separate the different types of output into different files. Sorry about that.

**Comment by rjbgoudie** [comment]
Great, thanks for clarifying
